<a href="https://colab.research.google.com/github/shcho11/Python_Basics_memo3/blob/main/numpy_practice_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy 기초

In [ ]:
import numpy as np

In [ ]:
data1 = [10,9.9,9.8,10,10]

In [ ]:
arr1 = np.array(data1)

In [ ]:
arr1

array([10. ,  9.9,  9.8, 10. , 10. ])

In [ ]:
arr1.dtype

dtype('float64')

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [ ]:
data2

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [ ]:
arr2 = np.array(data2)

In [ ]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2.dtype

dtype('int32')

In [ ]:
arr3 = np.arange(10) #np.arange(0,10,1)

In [ ]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
type(arr3)

numpy.ndarray

In [ ]:
type(data2)

list

In [ ]:
arr = np.array([1,2,3,4,5], dtype=np.int64)

In [ ]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
floar_arr = arr.astype(np.float32)

In [ ]:
floar_arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [ ]:
arr1 = np.array([[1,2,3],[4,5,6]], dtype=np.float64)

In [ ]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
arr2 = np.array([[10,20,30],[40,50,60]], dtype=np.float64) 

In [ ]:
arr2

array([[10., 20., 30.],
       [40., 50., 60.]])

In [ ]:
arr1 + arr2

array([[11., 22., 33.],
       [44., 55., 66.]])

In [ ]:
arr1 * arr2

array([[ 10.,  40.,  90.],
       [160., 250., 360.]])

In [ ]:
#벡터와 스칼라간의 곱 연산
arr1 * 2

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [ ]:
arr1 **2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [ ]:
names = np.array(['cho','song','hyun','david','jonathan'])

In [ ]:
names

array(['cho', 'song', 'hyun', 'david', 'jonathan'], dtype='<U8')

In [ ]:
names.dtype

dtype('<U8')

In [ ]:
type(names)

numpy.ndarray

In [ ]:
data = np.random.randn(5,4)

In [ ]:
data

array([[ 0.01667481,  0.2455534 ,  0.19498008,  2.14069993],
       [-1.97843017, -0.64805707, -0.25169907, -0.41253017],
       [ 1.79925581, -1.38057416, -0.37279094, -0.82383843],
       [ 0.79799895, -0.28263644, -2.01753511,  1.20390434],
       [ 0.18333869, -1.03648016,  0.17967482,  0.61383149]])

In [ ]:
names == 'song'

array([False,  True, False, False, False])

In [ ]:
data[names == 'song',:]

array([[-1.97843017, -0.64805707, -0.25169907, -0.41253017]])

In [ ]:
data[:,0:2]

array([[ 0.01667481,  0.2455534 ],
       [-1.97843017, -0.64805707],
       [ 1.79925581, -1.38057416],
       [ 0.79799895, -0.28263644],
       [ 0.18333869, -1.03648016]])

In [ ]:
data[:,3] < 0

array([False,  True,  True, False, False])

In [ ]:
data[data[:,3] < 0, :]

array([[-1.97843017, -0.64805707, -0.25169907, -0.41253017],
       [ 1.79925581, -1.38057416, -0.37279094, -0.82383843]])

In [ ]:
data[data[:,3] < 0, 3] = 0

In [ ]:
data

array([[ 0.01667481,  0.2455534 ,  0.19498008,  2.14069993],
       [-1.97843017, -0.64805707, -0.25169907,  0.        ],
       [ 1.79925581, -1.38057416, -0.37279094,  0.        ],
       [ 0.79799895, -0.28263644, -2.01753511,  1.20390434],
       [ 0.18333869, -1.03648016,  0.17967482,  0.61383149]])

In [ ]:
c = np.array([1,2,3,4,5])
d = np.array([6,7,8,9,10])

In [ ]:
print(c+d)

[ 7  9 11 13 15]


In [ ]:
c*2

array([ 2,  4,  6,  8, 10])

In [ ]:
#벡터의 차원이 다르면 연산이 안됨
e = np.array([1,2,3,4,5])
f = np.array([6,7,8,9,10,11,12])
print(e+f)

ValueError: operands could not be broadcast together with shapes (5,) (7,) 