<a href="https://colab.research.google.com/github/shcho11/Python_Basics_memo3/blob/main/numpy_practice_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- np.random
- np.maximum, np.minimum
- sum
- np.sort

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(1,10)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
x = np.random.rand(10)
x

array([0.83659482, 0.43727204, 0.93161278, 0.59407009, 0.36319918,
       0.0477836 , 0.17342884, 0.60840014, 0.2961936 , 0.88360679])

In [ ]:
y = np.random.rand(10)
y

array([0.68999746, 0.29823347, 0.40456263, 0.5447324 , 0.41230816,
       0.96630585, 0.42519319, 0.1736493 , 0.00137678, 0.95097889])

In [ ]:
np.maximum(x,y)

array([0.83659482, 0.43727204, 0.93161278, 0.59407009, 0.41230816,
       0.96630585, 0.42519319, 0.60840014, 0.2961936 , 0.95097889])

In [ ]:
np.minimum(x,y)

array([0.68999746, 0.29823347, 0.40456263, 0.5447324 , 0.36319918,
       0.0477836 , 0.17342884, 0.1736493 , 0.00137678, 0.88360679])

In [ ]:
arr2 = np.random.randn(6,5)
arr2

array([[ 0.42773586, -0.51454068,  0.44627383, -0.50558031,  2.21097026],
       [-0.2200519 ,  0.10215365, -2.39461396, -0.67145485, -0.85246024],
       [-1.35423039,  0.35054668, -1.18923023, -2.28375327, -0.06880164],
       [-0.24302008,  0.68764354, -1.06211358,  0.00390069,  0.69333203],
       [-0.67856939, -0.7261563 ,  0.48431421, -0.87401376,  0.12801282],
       [-0.14920468,  0.65863312,  0.96376887, -0.84586193,  0.69100339]])

In [ ]:
arr2.sum()

-6.78536824326487

In [ ]:
arr2.sum(axis=0)

array([-2.21734058,  0.55828   , -2.75160085, -5.17676343,  2.80205661])

In [ ]:
arr2.sum(axis=1)

array([ 2.06485896, -4.03642731, -4.54546885,  0.0797426 , -1.66641242,
        1.31833876])

In [ ]:
arr3 = np.random.randn(7)

In [ ]:
arr3

array([-0.36331144, -0.46785261, -0.84464839, -0.08542202, -0.94943851,
       -1.69858629,  1.62700066])

In [ ]:
arr3.sort()

In [ ]:
arr3

array([-1.69858629, -0.94943851, -0.84464839, -0.46785261, -0.36331144,
       -0.08542202,  1.62700066])

In [ ]:
arr4 = np.random.randn(5,3)

In [ ]:
arr4

array([[ 8.42754197e-01, -2.05522098e-01,  1.03970335e+00],
       [ 1.98088034e-01, -1.02955126e-03,  3.19913083e-01],
       [-6.81520299e-01,  1.16291893e+00, -1.19308267e+00],
       [ 1.03842729e+00,  5.00703174e-01,  2.16356934e+00],
       [-8.99851304e-01, -4.66031031e-01,  2.22626097e+00]])

In [ ]:
np.sort(arr4, axis=0)

array([[-8.99851304e-01, -4.66031031e-01, -1.19308267e+00],
       [-6.81520299e-01, -2.05522098e-01,  3.19913083e-01],
       [ 1.98088034e-01, -1.02955126e-03,  1.03970335e+00],
       [ 8.42754197e-01,  5.00703174e-01,  2.16356934e+00],
       [ 1.03842729e+00,  1.16291893e+00,  2.22626097e+00]])

In [ ]:
np.sort(arr4, axis=1)

array([[-2.05522098e-01,  8.42754197e-01,  1.03970335e+00],
       [-1.02955126e-03,  1.98088034e-01,  3.19913083e-01],
       [-1.19308267e+00, -6.81520299e-01,  1.16291893e+00],
       [ 5.00703174e-01,  1.03842729e+00,  2.16356934e+00],
       [-8.99851304e-01, -4.66031031e-01,  2.22626097e+00]])